@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":LibraryParser" as LibraryParser LOGIC_COLOR
participant ":AddProblemCommandParser" as AddProblemCommandParser LOGIC_COLOR
participant "d:AddProblemCommand" as AddProblemCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("report severity/high problem/book is broken")
activate LogicManager

LogicManager -> LibraryParser : parseCommand("report severity/high problem/book is broken")
activate LibraryParser

create AddProblemCommandParser
LibraryParser -> AddProblemCommandParser
activate AddProblemCommandParser

AddProblemCommandParser --> LibraryParser
deactivate AddProblemCommandParser

LibraryParser -> AddProblemCommandParser : parse("severity/high problem/book is broken")
activate AddProblemCommandParser

create AddProblemCommand
AddProblemCommandParser -> AddProblemCommand
activate AddProblemCommand

AddProblemCommand --> AddProblemCommandParser : d
deactivate AddProblemCommand

AddProblemCommandParser --> LibraryParser : d
deactivate AddProblemCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddProblemCommandParser -[hidden]-> LibraryParser
destroy AddProblemCommandParser

LibraryParser --> LogicManager : d
deactivate LibraryParser

LogicManager -> AddProblemCommand : execute()
activate AddProblemCommand

AddProblemCommand -> Model : addProblem(problem)
activate Model

Model --> AddProblemCommand
deactivate Model

create CommandResult
AddProblemCommand -> CommandResult
activate CommandResult

CommandResult --> AddProblemCommand
deactivate CommandResult

AddProblemCommand --> LogicManager : result
deactivate AddProblemCommand

[<--LogicManager
deactivate LogicManager
@enduml
