@startuml
!include style.puml

box Logic LOGIC_COLOR_T1

participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "<<class>>\n:ParseUtil" as ParserUtil LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant "s:Stocking" as Stocking LOGIC_COLOR
end box

[-> AddCommandParser : parse("...")
activate AddCommandParser

AddCommandParser -> ParserUtil : parseStocking("science library 10 central library 30")
activate ParserUtil

create Stocking
ParserUtil -> Stocking
activate Stocking

Stocking --> ParserUtil : s
deactivate Stocking

ParserUtil -> AddCommandParser : s
deactivate ParserUtil

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

[<--AddCommandParser : a
deactivate AddCommandParser
[<-[hidden]- AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
destroy AddCommandParser

@enduml
