@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueCategoryList
UniqueCategoryList -[hidden]down- UniquePersonList
UniqueCategoryList -[hidden]down- UniquePersonList

UniqueCategoryList *-right-> "*" Category
UniquePersonList o-right-> Person

Person -up-> "*" Category

Person *--> Name
Person *--> Isbn
Person *--> Email
Person *--> Address
@enduml
