@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteByCommandParser" as DeleteByCommandParser LOGIC_COLOR
participant "d:DeleteByCommand" as DeleteByCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteBy n/Linear Algebra")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteBy n/Linear Algebra")
activate AddressBookParser

create DeleteByByCommandParser
AddressBookParser -> DeleteByByCommandParser
activate DeleteByCommandParser

DeleteByCommandParser --> AddressBookParser
deactivate DeleteByCommandParser

AddressBookParser -> DeleteByCommandParser : parse("Linear Algebra")
activate DeleteByCommandParser

create DeleteByCommand
DeleteByCommandParser -> DeleteByCommand
activate DeleteByCommand

DeleteByCommand --> DeleteByCommandParser : d
deactivate DeleteByCommand

DeleteByCommandParser --> AddressBookParser : d
deactivate DeleteByCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteByCommandParser -[hidden]-> AddressBookParser
destroy DeleteByCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteByCommand : execute()
activate DeleteByCommand

DeleteByCommand -> Model : deleteByBook(1)
activate Model

Model --> DeleteByCommand
deactivate Model

create CommandResult
DeleteByCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteByCommand
deactivate CommandResult

DeleteByCommand --> LogicManager : result
deactivate DeleteByCommand

[<--LogicManager
deactivate LogicManager
@enduml
