@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Book -up-> "*" Category

Book *--> Name
Book *--> Isbn
Book *--> Email
Book *--> Language
Book *--> Stocking
Book *-right-> "*" Review
Stocking *--> Storage
Storage *--> CentralLibraryStorage
Storage *--> ScienceLibraryStorage
Storage *--> HSSMLibraryStorage
Book *--> Publisher
Book *--> Author
Book *--> Times
@enduml
