@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyLibrary <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Library
Class ReadOnlyLibrary
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Book {
Class Book
Class Language
Class Email
Class Name
Class Isbn
Class UniqueBookList
}

Package Category {
Class Category
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Library .up.|> ReadOnlyLibrary

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Library
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Library *--> "1" UniqueBookList
UniqueBookList o--> "*" Book
Book *--> Name
Book *--> Isbn
Book *--> Email
Book *--> Language
Book *--> "*" Category

Name -[hidden]right-> Isbn
Isbn -[hidden]right-> Language
Language -[hidden]right-> Email

ModelManager -->"1" Book : filtered list
@enduml
