@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class BookListPanel
Class BookCardWithCover
Class StatusBarFooter
Class CommandBox
Class LibraryBookDetailReviewCard
Class LibraryBookDetailStockingCard
Class ProblemReportListCard
Class ProblemReportListPanel
Class BookCoverManager
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> BookListPanel

BookCardWithCover -> BookCoverManager
BookListPanel -down-> BookCardWithCover

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
BookListPanel --|> UiPart
BookCardWithCover --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart
LibraryBookDetailReviewCard -up-|> UiPart
LibraryBookDetailStockingCard -up-|> UiPart
ProblemReportListCard -up-|> UiPart
ProblemReportListPanel -up-|> UiPart
BookCoverManager -up-|> UiPart

BookCardWithCover ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

BookListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
