@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":LanguageBookParser" as LanguageBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedLanguageBook" as VersionedLanguageBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> LanguageBookParser : parseCommand(undo)
activate LanguageBookParser

create UndoCommand
LanguageBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> LanguageBookParser
deactivate UndoCommand

LanguageBookParser --> LogicManager : u
deactivate LanguageBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoLanguageBook()
activate Model

Model -> VersionedLanguageBook : undo()
activate VersionedLanguageBook

VersionedLanguageBook -> VersionedLanguageBook :resetData(ReadOnlyLanguageBook)
VersionedLanguageBook --> Model :
deactivate VersionedLanguageBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
