@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressbookParser" as AddressbookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedAddressbook" as VersionedAddressbook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> AddressbookParser : parseCommand(undo)
activate AddressbookParser

create UndoCommand
AddressbookParser -> UndoCommand
activate UndoCommand

UndoCommand --> AddressbookParser
deactivate UndoCommand

AddressbookParser --> LogicManager : u
deactivate AddressbookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoAddressbook()
activate Model

Model -> VersionedAddressbook : undo()
activate VersionedAddressbook

VersionedAddressbook -> VersionedAddressbook :resetData(ReadOnlyAddressbook)
VersionedAddressbook --> Model :
deactivate VersionedAddressbook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
